/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


namespace OriginalCircuit.DigiKey.Api.Model
{
    /// <summary>
    /// Keyword Search Request object
    /// </summary>
    [DataContract]
    public partial class ManufacturerProductDetailsRequest : IEquatable<ManufacturerProductDetailsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManufacturerProductDetailsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ManufacturerProductDetailsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ManufacturerProductDetailsRequest" /> class.
        /// </summary>
        /// <param name="manufacturerProduct">Manufacturer product name to search on.(required).</param>
        /// <param name="recordCount">Number of products to return between 1 and 50..</param>
        /// <param name="recordStartPosition">The starting index of the records returned. This is used to paginate beyond 50 results..</param>
        /// <param name="filters">filters.</param>
        /// <param name="sort">sort.</param>
        /// <param name="requestedQuantity">The quantity of the product you are looking to purchase. This is used with the SortByUnitPrice SortOption as price varies at differing quantities..</param>
        /// <param name="searchOptions">Filters the search results by the included SearchOption..</param>
        public ManufacturerProductDetailsRequest(string manufacturerProduct = default(string), int? recordCount = default(int?), int? recordStartPosition = default(int?), Filters filters = default(Filters), SortParameters sort = default(SortParameters), int? requestedQuantity = default(int?), List<SearchOption> searchOptions = default(List<SearchOption>))
        {
            // to ensure "manufacturerProduct" is required(not null)
            if (manufacturerProduct == null)
            {
                throw new InvalidDataException("manufacturerProduct is a required property for ManufacturerProductDetailsRequest and cannot be null");
            }
            else
            {
                this.ManufacturerProduct = manufacturerProduct;
            }
            this.RecordCount = recordCount;
            this.RecordStartPosition = recordStartPosition;
            this.Filters = filters;
            this.Sort = sort;
            this.RequestedQuantity = requestedQuantity;
            this.SearchOptions = searchOptions;
        }

        /// <summary>
        /// Manufacturer product name to search on.
        /// </summary>
        /// <value>Manufacturer product name to search on.</value>
        [DataMember(Name = "ManufacturerProduct", EmitDefaultValue = false)]
        public string ManufacturerProduct { get; set; }

        /// <summary>
        /// Number of products to return between 1 and 50.
        /// </summary>
        /// <value>Number of products to return between 1 and 50.</value>
        [DataMember(Name = "RecordCount", EmitDefaultValue = false)]
        public int? RecordCount { get; set; }

        /// <summary>
        /// The starting index of the records returned. This is used to paginate beyond 50 results.
        /// </summary>
        /// <value>The starting index of the records returned. This is used to paginate beyond 50 results.</value>
        [DataMember(Name = "RecordStartPosition", EmitDefaultValue = false)]
        public int? RecordStartPosition { get; set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [DataMember(Name = "Filters", EmitDefaultValue = false)]
        public Filters Filters { get; set; }

        /// <summary>
        /// Gets or Sets Sort
        /// </summary>
        [DataMember(Name = "Sort", EmitDefaultValue = false)]
        public SortParameters Sort { get; set; }

        /// <summary>
        /// The quantity of the product you are looking to purchase. This is used with the SortByUnitPrice SortOption as price varies at differing quantities.
        /// </summary>
        /// <value>The quantity of the product you are looking to purchase. This is used with the SortByUnitPrice SortOption as price varies at differing quantities.</value>
        [DataMember(Name = "RequestedQuantity", EmitDefaultValue = false)]
        public int? RequestedQuantity { get; set; }

        /// <summary>
        /// Filters the search results by the included SearchOption.
        /// </summary>
        /// <value>Filters the search results by the included SearchOption.</value>
        [DataMember(Name = "SearchOptions", EmitDefaultValue = false)]
        public List<SearchOption> SearchOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManufacturerProductDetailsRequest {\n");
            sb.Append("  ManufacturerProduct: ").Append(ManufacturerProduct).Append("\n");
            sb.Append("  RecordCount: ").Append(RecordCount).Append("\n");
            sb.Append("  RecordStartPosition: ").Append(RecordStartPosition).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  Sort: ").Append(Sort).Append("\n");
            sb.Append("  RequestedQuantity: ").Append(RequestedQuantity).Append("\n");
            sb.Append("  SearchOptions: ").Append(SearchOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ManufacturerProductDetailsRequest);
        }

        /// <summary>
        /// Returns true if ManufacturerProductDetailsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ManufacturerProductDetailsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManufacturerProductDetailsRequest input)
        {
            if (input == null)
                return false;

            return
               (
                    this.ManufacturerProduct == input.ManufacturerProduct ||
                   (this.ManufacturerProduct != null &&
                    this.ManufacturerProduct.Equals(input.ManufacturerProduct))
                ) &&
               (
                    this.RecordCount == input.RecordCount ||
                   (this.RecordCount != null &&
                    this.RecordCount.Equals(input.RecordCount))
                ) &&
               (
                    this.RecordStartPosition == input.RecordStartPosition ||
                   (this.RecordStartPosition != null &&
                    this.RecordStartPosition.Equals(input.RecordStartPosition))
                ) &&
               (
                    this.Filters == input.Filters ||
                   (this.Filters != null &&
                    this.Filters.Equals(input.Filters))
                ) &&
               (
                    this.Sort == input.Sort ||
                   (this.Sort != null &&
                    this.Sort.Equals(input.Sort))
                ) &&
               (
                    this.RequestedQuantity == input.RequestedQuantity ||
                   (this.RequestedQuantity != null &&
                    this.RequestedQuantity.Equals(input.RequestedQuantity))
                ) &&
               (
                    this.SearchOptions == input.SearchOptions ||
                    this.SearchOptions != null &&
                    this.SearchOptions.SequenceEqual(input.SearchOptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ManufacturerProduct != null)
                    hashCode = hashCode * 59 + this.ManufacturerProduct.GetHashCode();
                if (this.RecordCount != null)
                    hashCode = hashCode * 59 + this.RecordCount.GetHashCode();
                if (this.RecordStartPosition != null)
                    hashCode = hashCode * 59 + this.RecordStartPosition.GetHashCode();
                if (this.Filters != null)
                    hashCode = hashCode * 59 + this.Filters.GetHashCode();
                if (this.Sort != null)
                    hashCode = hashCode * 59 + this.Sort.GetHashCode();
                if (this.RequestedQuantity != null)
                    hashCode = hashCode * 59 + this.RequestedQuantity.GetHashCode();
                if (this.SearchOptions != null)
                    hashCode = hashCode * 59 + this.SearchOptions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ManufacturerProduct(string) maxLength
            if (this.ManufacturerProduct != null && this.ManufacturerProduct.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ManufacturerProduct, length must be less than 250.", new[] { "ManufacturerProduct" });
            }

            // ManufacturerProduct(string) minLength
            if (this.ManufacturerProduct != null && this.ManufacturerProduct.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ManufacturerProduct, length must be greater than 1.", new[] { "ManufacturerProduct" });
            }

            // RecordCount(int?) maximum
            if (this.RecordCount > (int?)50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RecordCount, must be a value less than or equal to 50.", new[] { "RecordCount" });
            }

            // RecordCount(int?) minimum
            if (this.RecordCount < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RecordCount, must be a value greater than or equal to 1.", new[] { "RecordCount" });
            }

            yield break;
        }
    }

}
