/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


namespace DigiKey.Api.Model
{
    /// <summary>
    /// List of Manufacturers and information about each manufacturer
    /// </summary>
    [DataContract]
    public partial class ManufacturersResponse : IEquatable<ManufacturersResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManufacturersResponse" /> class.
        /// </summary>
        /// <param name="manufacturers">List of Manufacturer Information.</param>
        public ManufacturersResponse(List<ManufacturerInfo> manufacturers = default(List<ManufacturerInfo>))
        {
            this.Manufacturers = manufacturers;
        }

        /// <summary>
        /// List of Manufacturer Information
        /// </summary>
        /// <value>List of Manufacturer Information</value>
        [DataMember(Name = "Manufacturers", EmitDefaultValue = false)]
        public List<ManufacturerInfo> Manufacturers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManufacturersResponse {\n");
            sb.Append("  Manufacturers: ").Append(Manufacturers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ManufacturersResponse);
        }

        /// <summary>
        /// Returns true if ManufacturersResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ManufacturersResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManufacturersResponse input)
        {
            if (input == null)
                return false;

            return
               (
                    this.Manufacturers == input.Manufacturers ||
                    this.Manufacturers != null &&
                    this.Manufacturers.SequenceEqual(input.Manufacturers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Manufacturers != null)
                    hashCode = hashCode * 59 + this.Manufacturers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
