/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;


namespace OriginalCircuit.DigiKey.Api.Model
{
    /// <summary>
    /// A filter used to refine a keyword search on any parameter.
    /// </summary>
    [DataContract]
    public partial class ParametricFilter : IEquatable<ParametricFilter>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParametricFilter" /> class.
        /// </summary>
        /// <param name="parameterId">The parameter identifier..</param>
        /// <param name="valueId">The value identifier..</param>
        public ParametricFilter(int? parameterId = default(int?), string valueId = default(string))
        {
            this.ParameterId = parameterId;
            this.ValueId = valueId;
        }

        /// <summary>
        /// The parameter identifier.
        /// </summary>
        /// <value>The parameter identifier.</value>
        [DataMember(Name = "ParameterId", EmitDefaultValue = false)]
        public int? ParameterId { get; set; }

        /// <summary>
        /// The value identifier.
        /// </summary>
        /// <value>The value identifier.</value>
        [DataMember(Name = "ValueId", EmitDefaultValue = false)]
        public string ValueId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParametricFilter {\n");
            sb.Append("  ParameterId: ").Append(ParameterId).Append("\n");
            sb.Append("  ValueId: ").Append(ValueId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParametricFilter);
        }

        /// <summary>
        /// Returns true if ParametricFilter instances are equal
        /// </summary>
        /// <param name="input">Instance of ParametricFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParametricFilter input)
        {
            if (input == null)
                return false;

            return
               (
                    this.ParameterId == input.ParameterId ||
                   (this.ParameterId != null &&
                    this.ParameterId.Equals(input.ParameterId))
                ) &&
               (
                    this.ValueId == input.ValueId ||
                   (this.ValueId != null &&
                    this.ValueId.Equals(input.ValueId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ParameterId != null)
                    hashCode = hashCode * 59 + this.ParameterId.GetHashCode();
                if (this.ValueId != null)
                    hashCode = hashCode * 59 + this.ValueId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ParameterId(int?) maximum
            if (this.ParameterId > (int?)2147483647)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ParameterId, must be a value less than or equal to 2147483647.", new[] { "ParameterId" });
            }

            // ParameterId(int?) minimum
            if (this.ParameterId < (int?)-2147483648)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ParameterId, must be a value greater than or equal to -2147483648.", new[] { "ParameterId" });
            }

            // ValueId(string) maxLength
            if (this.ValueId != null && this.ValueId.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ValueId, length must be less than 100.", new[] { "ValueId" });
            }

            // ValueId(string) minLength
            if (this.ValueId != null && this.ValueId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ValueId, length must be greater than 1.", new[] { "ValueId" });
            }

            yield break;
        }
    }

}
