/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


namespace OriginalCircuit.DigiKey.Api.Model
{
    /// <summary>
    /// Standard information about a product.
    /// </summary>
    [DataContract]
    public partial class Product : IEquatable<Product>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        /// <param name="standardPricing">Standard pricing for the validated locale..</param>
        /// <param name="roHSStatus">RoHS status. Can be: RoHS Compliant, RoHS non-compliant, RoHS Compliant By Exemption, Not Applicable, Vendor  undefined, Request Inventory Verification, ROHS3 Compliant..</param>
        /// <param name="leadStatus">Lead status. Can be: Lead Free, Contains lead, Lead Free By Exemption, Not Applicable, Vendor undefined, unknown,  or Request Inventory Verification..</param>
        /// <param name="parameters">Parameters for the part. Can be used for filtering keyword searches..</param>
        /// <param name="productUrl">Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values..</param>
        /// <param name="primaryDatasheet">The URL to the product&#39;s datasheet..</param>
        /// <param name="primaryPhoto">The URL to the product&#39;s image..</param>
        /// <param name="primaryVideo">The URL to the product&#39;s video..</param>
        /// <param name="series">series.</param>
        /// <param name="manufacturerLeadWeeks">The number of weeks expected to receive stock from manufacturer..</param>
        /// <param name="manufacturerPageUrl">The URL to Digi-Key&#39;s page on the manufacturer..</param>
        /// <param name="productStatus">Status of the product. Options include: Active, Obsolete, Discontinued at Digi-Key, Last Time Buy, Not For New  Designs, Preliminary. For obsolete parts the part will become a non-stocking item when stock is depleted; minimums  will apply. Order the quantity available or the quantity available plus a multiple of the minimum order quantity..</param>
        /// <param name="dateLastBuyChance">Last date that the product will be available for purchase. Date is in ISO 8601..</param>
        /// <param name="alternatePackaging">Other packaging types available for this product..</param>
        /// <param name="detailedDescription">Extended catalog description of the product..</param>
        /// <param name="reachStatus">REACH is a regulation of the European Union. See documentation from the European Chemicals Agency..</param>
        /// <param name="exportControlClassNumber">Export control class number. See documentation from the U.S. Department of Commerce..</param>
        /// <param name="hTSUSCode">Harmonized Tariff Schedule of the United States. See documentation from the U.S. International Trade Commission..</param>
        /// <param name="tariffDescription">Description of the tariff status. Only applies if purchasing in USD and shipping to the US. Valid options are No  Tariff and Tariff Applied..</param>
        /// <param name="moistureSensitivityLevel">Code for Moisture Sensitivity Level of the product.</param>
        /// <param name="family">family.</param>
        /// <param name="category">category.</param>
        /// <param name="manufacturerPartNumber">The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for  different parts..</param>
        /// <param name="minimumOrderQuantity">The minimum quantity to order from Digi-Key..</param>
        /// <param name="nonStock">Indicates this product is a non stock product..</param>
        /// <param name="packaging">packaging.</param>
        /// <param name="quantityAvailable">Quantity of the product available for immediate sale..</param>
        /// <param name="digiKeyPartNumber">The Digi-Key part number..</param>
        /// <param name="productDescription">Catalog description of the product..</param>
        /// <param name="unitPrice">The price for a single unit of this product..</param>
        /// <param name="manufacturer">manufacturer.</param>
        /// <param name="manufacturerPublicQuantity">Quantity of this product available to order from manufacturer..</param>
        /// <param name="quantityOnOrder">Quantity of this product ordered but not immediately available..</param>
        /// <param name="dKPlusRestriction">If true- this product is not available for purchase through the Ordering API - it must be purchased through the  Digi-Key web site.</param>
        /// <param name="marketplace">Product is a Marketplace product that ships direct from the supplier.  A separate shipping fee may apply.</param>
        /// <param name="supplierDirectShip">If true- this product is shipped directly from the Supplier.</param>
        /// <param name="pimProductName">Pim name for the product.</param>
        /// <param name="supplier">The Supplier is the provider of the products to Digi-Key and some cases the customer directly..</param>
        /// <param name="supplierId">Id for Supplier.</param>
        public Product(List<PriceBreak> standardPricing = default(List<PriceBreak>), string roHSStatus = default(string), string leadStatus = default(string), List<PidVid> parameters = default(List<PidVid>), string productUrl = default(string), string primaryDatasheet = default(string), string primaryPhoto = default(string), string primaryVideo = default(string), PidVid series = default(PidVid), string manufacturerLeadWeeks = default(string), string manufacturerPageUrl = default(string), string productStatus = default(string), DateTime? dateLastBuyChance = default(DateTime?), List<BasicProduct> alternatePackaging = default(List<BasicProduct>), string detailedDescription = default(string), string reachStatus = default(string), string exportControlClassNumber = default(string), string hTSUSCode = default(string), string tariffDescription = default(string), string moistureSensitivityLevel = default(string), PidVid family = default(PidVid), PidVid category = default(PidVid), string manufacturerPartNumber = default(string), int? minimumOrderQuantity = default(int?), bool? nonStock = default(bool?), PidVid packaging = default(PidVid), int? quantityAvailable = default(int?), string digiKeyPartNumber = default(string), string productDescription = default(string), double? unitPrice = default(double?), PidVid manufacturer = default(PidVid), int? manufacturerPublicQuantity = default(int?), int? quantityOnOrder = default(int?), bool? dKPlusRestriction = default(bool?), bool? marketplace = default(bool?), bool? supplierDirectShip = default(bool?), string pimProductName = default(string), string supplier = default(string), int? supplierId = default(int?))
        {
            this.StandardPricing = standardPricing;
            this.RoHSStatus = roHSStatus;
            this.LeadStatus = leadStatus;
            this.Parameters = parameters;
            this.ProductUrl = productUrl;
            this.PrimaryDatasheet = primaryDatasheet;
            this.PrimaryPhoto = primaryPhoto;
            this.PrimaryVideo = primaryVideo;
            this.Series = series;
            this.ManufacturerLeadWeeks = manufacturerLeadWeeks;
            this.ManufacturerPageUrl = manufacturerPageUrl;
            this.ProductStatus = productStatus;
            this.DateLastBuyChance = dateLastBuyChance;
            this.AlternatePackaging = alternatePackaging;
            this.DetailedDescription = detailedDescription;
            this.ReachStatus = reachStatus;
            this.ExportControlClassNumber = exportControlClassNumber;
            this.HTSUSCode = hTSUSCode;
            this.TariffDescription = tariffDescription;
            this.MoistureSensitivityLevel = moistureSensitivityLevel;
            this.Family = family;
            this.Category = category;
            this.ManufacturerPartNumber = manufacturerPartNumber;
            this.MinimumOrderQuantity = minimumOrderQuantity;
            this.NonStock = nonStock;
            this.Packaging = packaging;
            this.QuantityAvailable = quantityAvailable;
            this.DigiKeyPartNumber = digiKeyPartNumber;
            this.ProductDescription = productDescription;
            this.UnitPrice = unitPrice;
            this.Manufacturer = manufacturer;
            this.ManufacturerPublicQuantity = manufacturerPublicQuantity;
            this.QuantityOnOrder = quantityOnOrder;
            this.DKPlusRestriction = dKPlusRestriction;
            this.Marketplace = marketplace;
            this.SupplierDirectShip = supplierDirectShip;
            this.PimProductName = pimProductName;
            this.Supplier = supplier;
            this.SupplierId = supplierId;
        }

        /// <summary>
        /// Standard pricing for the validated locale.
        /// </summary>
        /// <value>Standard pricing for the validated locale.</value>
        [DataMember(Name = "StandardPricing", EmitDefaultValue = false)]
        public List<PriceBreak> StandardPricing { get; set; }

        /// <summary>
        /// RoHS status. Can be: RoHS Compliant, RoHS non-compliant, RoHS Compliant By Exemption, Not Applicable, Vendor  undefined, Request Inventory Verification, ROHS3 Compliant.
        /// </summary>
        /// <value>RoHS status. Can be: RoHS Compliant, RoHS non-compliant, RoHS Compliant By Exemption, Not Applicable, Vendor  undefined, Request Inventory Verification, ROHS3 Compliant.</value>
        [DataMember(Name = "RoHSStatus", EmitDefaultValue = false)]
        public string RoHSStatus { get; set; }

        /// <summary>
        /// Lead status. Can be: Lead Free, Contains lead, Lead Free By Exemption, Not Applicable, Vendor undefined, unknown,  or Request Inventory Verification.
        /// </summary>
        /// <value>Lead status. Can be: Lead Free, Contains lead, Lead Free By Exemption, Not Applicable, Vendor undefined, unknown,  or Request Inventory Verification.</value>
        [DataMember(Name = "LeadStatus", EmitDefaultValue = false)]
        public string LeadStatus { get; set; }

        /// <summary>
        /// Parameters for the part. Can be used for filtering keyword searches.
        /// </summary>
        /// <value>Parameters for the part. Can be used for filtering keyword searches.</value>
        [DataMember(Name = "Parameters", EmitDefaultValue = false)]
        public List<PidVid> Parameters { get; set; }

        /// <summary>
        /// Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.
        /// </summary>
        /// <value>Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.</value>
        [DataMember(Name = "ProductUrl", EmitDefaultValue = false)]
        public string ProductUrl { get; set; }

        /// <summary>
        /// The URL to the product&#39;s datasheet.
        /// </summary>
        /// <value>The URL to the product&#39;s datasheet.</value>
        [DataMember(Name = "PrimaryDatasheet", EmitDefaultValue = false)]
        public string PrimaryDatasheet { get; set; }

        /// <summary>
        /// The URL to the product&#39;s image.
        /// </summary>
        /// <value>The URL to the product&#39;s image.</value>
        [DataMember(Name = "PrimaryPhoto", EmitDefaultValue = false)]
        public string PrimaryPhoto { get; set; }

        /// <summary>
        /// The URL to the product&#39;s video.
        /// </summary>
        /// <value>The URL to the product&#39;s video.</value>
        [DataMember(Name = "PrimaryVideo", EmitDefaultValue = false)]
        public string PrimaryVideo { get; set; }

        /// <summary>
        /// Gets or Sets Series
        /// </summary>
        [DataMember(Name = "Series", EmitDefaultValue = false)]
        public PidVid Series { get; set; }

        /// <summary>
        /// The number of weeks expected to receive stock from manufacturer.
        /// </summary>
        /// <value>The number of weeks expected to receive stock from manufacturer.</value>
        [DataMember(Name = "ManufacturerLeadWeeks", EmitDefaultValue = false)]
        public string ManufacturerLeadWeeks { get; set; }

        /// <summary>
        /// The URL to Digi-Key&#39;s page on the manufacturer.
        /// </summary>
        /// <value>The URL to Digi-Key&#39;s page on the manufacturer.</value>
        [DataMember(Name = "ManufacturerPageUrl", EmitDefaultValue = false)]
        public string ManufacturerPageUrl { get; set; }

        /// <summary>
        /// Status of the product. Options include: Active, Obsolete, Discontinued at Digi-Key, Last Time Buy, Not For New  Designs, Preliminary. For obsolete parts the part will become a non-stocking item when stock is depleted; minimums  will apply. Order the quantity available or the quantity available plus a multiple of the minimum order quantity.
        /// </summary>
        /// <value>Status of the product. Options include: Active, Obsolete, Discontinued at Digi-Key, Last Time Buy, Not For New  Designs, Preliminary. For obsolete parts the part will become a non-stocking item when stock is depleted; minimums  will apply. Order the quantity available or the quantity available plus a multiple of the minimum order quantity.</value>
        [DataMember(Name = "ProductStatus", EmitDefaultValue = false)]
        public string ProductStatus { get; set; }

        /// <summary>
        /// Last date that the product will be available for purchase. Date is in ISO 8601.
        /// </summary>
        /// <value>Last date that the product will be available for purchase. Date is in ISO 8601.</value>
        [DataMember(Name = "DateLastBuyChance", EmitDefaultValue = false)]
        public DateTime? DateLastBuyChance { get; set; }

        /// <summary>
        /// Other packaging types available for this product.
        /// </summary>
        /// <value>Other packaging types available for this product.</value>
        [DataMember(Name = "AlternatePackaging", EmitDefaultValue = false)]
        public List<BasicProduct> AlternatePackaging { get; set; }

        /// <summary>
        /// Extended catalog description of the product.
        /// </summary>
        /// <value>Extended catalog description of the product.</value>
        [DataMember(Name = "DetailedDescription", EmitDefaultValue = false)]
        public string DetailedDescription { get; set; }

        /// <summary>
        /// REACH is a regulation of the European Union. See documentation from the European Chemicals Agency.
        /// </summary>
        /// <value>REACH is a regulation of the European Union. See documentation from the European Chemicals Agency.</value>
        [DataMember(Name = "ReachStatus", EmitDefaultValue = false)]
        public string ReachStatus { get; set; }

        /// <summary>
        /// Export control class number. See documentation from the U.S. Department of Commerce.
        /// </summary>
        /// <value>Export control class number. See documentation from the U.S. Department of Commerce.</value>
        [DataMember(Name = "ExportControlClassNumber", EmitDefaultValue = false)]
        public string ExportControlClassNumber { get; set; }

        /// <summary>
        /// Harmonized Tariff Schedule of the United States. See documentation from the U.S. International Trade Commission.
        /// </summary>
        /// <value>Harmonized Tariff Schedule of the United States. See documentation from the U.S. International Trade Commission.</value>
        [DataMember(Name = "HTSUSCode", EmitDefaultValue = false)]
        public string HTSUSCode { get; set; }

        /// <summary>
        /// Description of the tariff status. Only applies if purchasing in USD and shipping to the US. Valid options are No  Tariff and Tariff Applied.
        /// </summary>
        /// <value>Description of the tariff status. Only applies if purchasing in USD and shipping to the US. Valid options are No  Tariff and Tariff Applied.</value>
        [DataMember(Name = "TariffDescription", EmitDefaultValue = false)]
        public string TariffDescription { get; set; }

        /// <summary>
        /// Code for Moisture Sensitivity Level of the product
        /// </summary>
        /// <value>Code for Moisture Sensitivity Level of the product</value>
        [DataMember(Name = "MoistureSensitivityLevel", EmitDefaultValue = false)]
        public string MoistureSensitivityLevel { get; set; }

        /// <summary>
        /// Gets or Sets Family
        /// </summary>
        [DataMember(Name = "Family", EmitDefaultValue = false)]
        public PidVid Family { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "Category", EmitDefaultValue = false)]
        public PidVid Category { get; set; }

        /// <summary>
        /// The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for  different parts.
        /// </summary>
        /// <value>The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for  different parts.</value>
        [DataMember(Name = "ManufacturerPartNumber", EmitDefaultValue = false)]
        public string ManufacturerPartNumber { get; set; }

        /// <summary>
        /// The minimum quantity to order from Digi-Key.
        /// </summary>
        /// <value>The minimum quantity to order from Digi-Key.</value>
        [DataMember(Name = "MinimumOrderQuantity", EmitDefaultValue = false)]
        public int? MinimumOrderQuantity { get; set; }

        /// <summary>
        /// Indicates this product is a non stock product.
        /// </summary>
        /// <value>Indicates this product is a non stock product.</value>
        [DataMember(Name = "NonStock", EmitDefaultValue = false)]
        public bool? NonStock { get; set; }

        /// <summary>
        /// Gets or Sets Packaging
        /// </summary>
        [DataMember(Name = "Packaging", EmitDefaultValue = false)]
        public PidVid Packaging { get; set; }

        /// <summary>
        /// Quantity of the product available for immediate sale.
        /// </summary>
        /// <value>Quantity of the product available for immediate sale.</value>
        [DataMember(Name = "QuantityAvailable", EmitDefaultValue = false)]
        public int? QuantityAvailable { get; set; }

        /// <summary>
        /// The Digi-Key part number.
        /// </summary>
        /// <value>The Digi-Key part number.</value>
        [DataMember(Name = "DigiKeyPartNumber", EmitDefaultValue = false)]
        public string DigiKeyPartNumber { get; set; }

        /// <summary>
        /// Catalog description of the product.
        /// </summary>
        /// <value>Catalog description of the product.</value>
        [DataMember(Name = "ProductDescription", EmitDefaultValue = false)]
        public string ProductDescription { get; set; }

        /// <summary>
        /// The price for a single unit of this product.
        /// </summary>
        /// <value>The price for a single unit of this product.</value>
        [DataMember(Name = "UnitPrice", EmitDefaultValue = false)]
        public double? UnitPrice { get; set; }

        /// <summary>
        /// Gets or Sets Manufacturer
        /// </summary>
        [DataMember(Name = "Manufacturer", EmitDefaultValue = false)]
        public PidVid Manufacturer { get; set; }

        /// <summary>
        /// Quantity of this product available to order from manufacturer.
        /// </summary>
        /// <value>Quantity of this product available to order from manufacturer.</value>
        [DataMember(Name = "ManufacturerPublicQuantity", EmitDefaultValue = false)]
        public int? ManufacturerPublicQuantity { get; set; }

        /// <summary>
        /// Quantity of this product ordered but not immediately available.
        /// </summary>
        /// <value>Quantity of this product ordered but not immediately available.</value>
        [DataMember(Name = "QuantityOnOrder", EmitDefaultValue = false)]
        public int? QuantityOnOrder { get; set; }

        /// <summary>
        /// If true- this product is not available for purchase through the Ordering API - it must be purchased through the  Digi-Key web site
        /// </summary>
        /// <value>If true- this product is not available for purchase through the Ordering API - it must be purchased through the  Digi-Key web site</value>
        [DataMember(Name = "DKPlusRestriction", EmitDefaultValue = false)]
        public bool? DKPlusRestriction { get; set; }

        /// <summary>
        /// Product is a Marketplace product that ships direct from the supplier.  A separate shipping fee may apply
        /// </summary>
        /// <value>Product is a Marketplace product that ships direct from the supplier.  A separate shipping fee may apply</value>
        [DataMember(Name = "Marketplace", EmitDefaultValue = false)]
        public bool? Marketplace { get; set; }

        /// <summary>
        /// If true- this product is shipped directly from the Supplier
        /// </summary>
        /// <value>If true- this product is shipped directly from the Supplier</value>
        [DataMember(Name = "SupplierDirectShip", EmitDefaultValue = false)]
        public bool? SupplierDirectShip { get; set; }

        /// <summary>
        /// Pim name for the product
        /// </summary>
        /// <value>Pim name for the product</value>
        [DataMember(Name = "PimProductName", EmitDefaultValue = false)]
        public string PimProductName { get; set; }

        /// <summary>
        /// The Supplier is the provider of the products to Digi-Key and some cases the customer directly.
        /// </summary>
        /// <value>The Supplier is the provider of the products to Digi-Key and some cases the customer directly.</value>
        [DataMember(Name = "Supplier", EmitDefaultValue = false)]
        public string Supplier { get; set; }

        /// <summary>
        /// Id for Supplier
        /// </summary>
        /// <value>Id for Supplier</value>
        [DataMember(Name = "SupplierId", EmitDefaultValue = false)]
        public int? SupplierId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Product {\n");
            sb.Append("  StandardPricing: ").Append(StandardPricing).Append("\n");
            sb.Append("  RoHSStatus: ").Append(RoHSStatus).Append("\n");
            sb.Append("  LeadStatus: ").Append(LeadStatus).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  ProductUrl: ").Append(ProductUrl).Append("\n");
            sb.Append("  PrimaryDatasheet: ").Append(PrimaryDatasheet).Append("\n");
            sb.Append("  PrimaryPhoto: ").Append(PrimaryPhoto).Append("\n");
            sb.Append("  PrimaryVideo: ").Append(PrimaryVideo).Append("\n");
            sb.Append("  Series: ").Append(Series).Append("\n");
            sb.Append("  ManufacturerLeadWeeks: ").Append(ManufacturerLeadWeeks).Append("\n");
            sb.Append("  ManufacturerPageUrl: ").Append(ManufacturerPageUrl).Append("\n");
            sb.Append("  ProductStatus: ").Append(ProductStatus).Append("\n");
            sb.Append("  DateLastBuyChance: ").Append(DateLastBuyChance).Append("\n");
            sb.Append("  AlternatePackaging: ").Append(AlternatePackaging).Append("\n");
            sb.Append("  DetailedDescription: ").Append(DetailedDescription).Append("\n");
            sb.Append("  ReachStatus: ").Append(ReachStatus).Append("\n");
            sb.Append("  ExportControlClassNumber: ").Append(ExportControlClassNumber).Append("\n");
            sb.Append("  HTSUSCode: ").Append(HTSUSCode).Append("\n");
            sb.Append("  TariffDescription: ").Append(TariffDescription).Append("\n");
            sb.Append("  MoistureSensitivityLevel: ").Append(MoistureSensitivityLevel).Append("\n");
            sb.Append("  Family: ").Append(Family).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  ManufacturerPartNumber: ").Append(ManufacturerPartNumber).Append("\n");
            sb.Append("  MinimumOrderQuantity: ").Append(MinimumOrderQuantity).Append("\n");
            sb.Append("  NonStock: ").Append(NonStock).Append("\n");
            sb.Append("  Packaging: ").Append(Packaging).Append("\n");
            sb.Append("  QuantityAvailable: ").Append(QuantityAvailable).Append("\n");
            sb.Append("  DigiKeyPartNumber: ").Append(DigiKeyPartNumber).Append("\n");
            sb.Append("  ProductDescription: ").Append(ProductDescription).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  ManufacturerPublicQuantity: ").Append(ManufacturerPublicQuantity).Append("\n");
            sb.Append("  QuantityOnOrder: ").Append(QuantityOnOrder).Append("\n");
            sb.Append("  DKPlusRestriction: ").Append(DKPlusRestriction).Append("\n");
            sb.Append("  Marketplace: ").Append(Marketplace).Append("\n");
            sb.Append("  SupplierDirectShip: ").Append(SupplierDirectShip).Append("\n");
            sb.Append("  PimProductName: ").Append(PimProductName).Append("\n");
            sb.Append("  Supplier: ").Append(Supplier).Append("\n");
            sb.Append("  SupplierId: ").Append(SupplierId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Product);
        }

        /// <summary>
        /// Returns true if Product instances are equal
        /// </summary>
        /// <param name="input">Instance of Product to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Product input)
        {
            if (input == null)
                return false;

            return
               (
                    this.StandardPricing == input.StandardPricing ||
                    this.StandardPricing != null &&
                    this.StandardPricing.SequenceEqual(input.StandardPricing)
                ) &&
               (
                    this.RoHSStatus == input.RoHSStatus ||
                   (this.RoHSStatus != null &&
                    this.RoHSStatus.Equals(input.RoHSStatus))
                ) &&
               (
                    this.LeadStatus == input.LeadStatus ||
                   (this.LeadStatus != null &&
                    this.LeadStatus.Equals(input.LeadStatus))
                ) &&
               (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) &&
               (
                    this.ProductUrl == input.ProductUrl ||
                   (this.ProductUrl != null &&
                    this.ProductUrl.Equals(input.ProductUrl))
                ) &&
               (
                    this.PrimaryDatasheet == input.PrimaryDatasheet ||
                   (this.PrimaryDatasheet != null &&
                    this.PrimaryDatasheet.Equals(input.PrimaryDatasheet))
                ) &&
               (
                    this.PrimaryPhoto == input.PrimaryPhoto ||
                   (this.PrimaryPhoto != null &&
                    this.PrimaryPhoto.Equals(input.PrimaryPhoto))
                ) &&
               (
                    this.PrimaryVideo == input.PrimaryVideo ||
                   (this.PrimaryVideo != null &&
                    this.PrimaryVideo.Equals(input.PrimaryVideo))
                ) &&
               (
                    this.Series == input.Series ||
                   (this.Series != null &&
                    this.Series.Equals(input.Series))
                ) &&
               (
                    this.ManufacturerLeadWeeks == input.ManufacturerLeadWeeks ||
                   (this.ManufacturerLeadWeeks != null &&
                    this.ManufacturerLeadWeeks.Equals(input.ManufacturerLeadWeeks))
                ) &&
               (
                    this.ManufacturerPageUrl == input.ManufacturerPageUrl ||
                   (this.ManufacturerPageUrl != null &&
                    this.ManufacturerPageUrl.Equals(input.ManufacturerPageUrl))
                ) &&
               (
                    this.ProductStatus == input.ProductStatus ||
                   (this.ProductStatus != null &&
                    this.ProductStatus.Equals(input.ProductStatus))
                ) &&
               (
                    this.DateLastBuyChance == input.DateLastBuyChance ||
                   (this.DateLastBuyChance != null &&
                    this.DateLastBuyChance.Equals(input.DateLastBuyChance))
                ) &&
               (
                    this.AlternatePackaging == input.AlternatePackaging ||
                    this.AlternatePackaging != null &&
                    this.AlternatePackaging.SequenceEqual(input.AlternatePackaging)
                ) &&
               (
                    this.DetailedDescription == input.DetailedDescription ||
                   (this.DetailedDescription != null &&
                    this.DetailedDescription.Equals(input.DetailedDescription))
                ) &&
               (
                    this.ReachStatus == input.ReachStatus ||
                   (this.ReachStatus != null &&
                    this.ReachStatus.Equals(input.ReachStatus))
                ) &&
               (
                    this.ExportControlClassNumber == input.ExportControlClassNumber ||
                   (this.ExportControlClassNumber != null &&
                    this.ExportControlClassNumber.Equals(input.ExportControlClassNumber))
                ) &&
               (
                    this.HTSUSCode == input.HTSUSCode ||
                   (this.HTSUSCode != null &&
                    this.HTSUSCode.Equals(input.HTSUSCode))
                ) &&
               (
                    this.TariffDescription == input.TariffDescription ||
                   (this.TariffDescription != null &&
                    this.TariffDescription.Equals(input.TariffDescription))
                ) &&
               (
                    this.MoistureSensitivityLevel == input.MoistureSensitivityLevel ||
                   (this.MoistureSensitivityLevel != null &&
                    this.MoistureSensitivityLevel.Equals(input.MoistureSensitivityLevel))
                ) &&
               (
                    this.Family == input.Family ||
                   (this.Family != null &&
                    this.Family.Equals(input.Family))
                ) &&
               (
                    this.Category == input.Category ||
                   (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) &&
               (
                    this.ManufacturerPartNumber == input.ManufacturerPartNumber ||
                   (this.ManufacturerPartNumber != null &&
                    this.ManufacturerPartNumber.Equals(input.ManufacturerPartNumber))
                ) &&
               (
                    this.MinimumOrderQuantity == input.MinimumOrderQuantity ||
                   (this.MinimumOrderQuantity != null &&
                    this.MinimumOrderQuantity.Equals(input.MinimumOrderQuantity))
                ) &&
               (
                    this.NonStock == input.NonStock ||
                   (this.NonStock != null &&
                    this.NonStock.Equals(input.NonStock))
                ) &&
               (
                    this.Packaging == input.Packaging ||
                   (this.Packaging != null &&
                    this.Packaging.Equals(input.Packaging))
                ) &&
               (
                    this.QuantityAvailable == input.QuantityAvailable ||
                   (this.QuantityAvailable != null &&
                    this.QuantityAvailable.Equals(input.QuantityAvailable))
                ) &&
               (
                    this.DigiKeyPartNumber == input.DigiKeyPartNumber ||
                   (this.DigiKeyPartNumber != null &&
                    this.DigiKeyPartNumber.Equals(input.DigiKeyPartNumber))
                ) &&
               (
                    this.ProductDescription == input.ProductDescription ||
                   (this.ProductDescription != null &&
                    this.ProductDescription.Equals(input.ProductDescription))
                ) &&
               (
                    this.UnitPrice == input.UnitPrice ||
                   (this.UnitPrice != null &&
                    this.UnitPrice.Equals(input.UnitPrice))
                ) &&
               (
                    this.Manufacturer == input.Manufacturer ||
                   (this.Manufacturer != null &&
                    this.Manufacturer.Equals(input.Manufacturer))
                ) &&
               (
                    this.ManufacturerPublicQuantity == input.ManufacturerPublicQuantity ||
                   (this.ManufacturerPublicQuantity != null &&
                    this.ManufacturerPublicQuantity.Equals(input.ManufacturerPublicQuantity))
                ) &&
               (
                    this.QuantityOnOrder == input.QuantityOnOrder ||
                   (this.QuantityOnOrder != null &&
                    this.QuantityOnOrder.Equals(input.QuantityOnOrder))
                ) &&
               (
                    this.DKPlusRestriction == input.DKPlusRestriction ||
                   (this.DKPlusRestriction != null &&
                    this.DKPlusRestriction.Equals(input.DKPlusRestriction))
                ) &&
               (
                    this.Marketplace == input.Marketplace ||
                   (this.Marketplace != null &&
                    this.Marketplace.Equals(input.Marketplace))
                ) &&
               (
                    this.SupplierDirectShip == input.SupplierDirectShip ||
                   (this.SupplierDirectShip != null &&
                    this.SupplierDirectShip.Equals(input.SupplierDirectShip))
                ) &&
               (
                    this.PimProductName == input.PimProductName ||
                   (this.PimProductName != null &&
                    this.PimProductName.Equals(input.PimProductName))
                ) &&
               (
                    this.Supplier == input.Supplier ||
                   (this.Supplier != null &&
                    this.Supplier.Equals(input.Supplier))
                ) &&
               (
                    this.SupplierId == input.SupplierId ||
                   (this.SupplierId != null &&
                    this.SupplierId.Equals(input.SupplierId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StandardPricing != null)
                    hashCode = hashCode * 59 + this.StandardPricing.GetHashCode();
                if (this.RoHSStatus != null)
                    hashCode = hashCode * 59 + this.RoHSStatus.GetHashCode();
                if (this.LeadStatus != null)
                    hashCode = hashCode * 59 + this.LeadStatus.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                if (this.ProductUrl != null)
                    hashCode = hashCode * 59 + this.ProductUrl.GetHashCode();
                if (this.PrimaryDatasheet != null)
                    hashCode = hashCode * 59 + this.PrimaryDatasheet.GetHashCode();
                if (this.PrimaryPhoto != null)
                    hashCode = hashCode * 59 + this.PrimaryPhoto.GetHashCode();
                if (this.PrimaryVideo != null)
                    hashCode = hashCode * 59 + this.PrimaryVideo.GetHashCode();
                if (this.Series != null)
                    hashCode = hashCode * 59 + this.Series.GetHashCode();
                if (this.ManufacturerLeadWeeks != null)
                    hashCode = hashCode * 59 + this.ManufacturerLeadWeeks.GetHashCode();
                if (this.ManufacturerPageUrl != null)
                    hashCode = hashCode * 59 + this.ManufacturerPageUrl.GetHashCode();
                if (this.ProductStatus != null)
                    hashCode = hashCode * 59 + this.ProductStatus.GetHashCode();
                if (this.DateLastBuyChance != null)
                    hashCode = hashCode * 59 + this.DateLastBuyChance.GetHashCode();
                if (this.AlternatePackaging != null)
                    hashCode = hashCode * 59 + this.AlternatePackaging.GetHashCode();
                if (this.DetailedDescription != null)
                    hashCode = hashCode * 59 + this.DetailedDescription.GetHashCode();
                if (this.ReachStatus != null)
                    hashCode = hashCode * 59 + this.ReachStatus.GetHashCode();
                if (this.ExportControlClassNumber != null)
                    hashCode = hashCode * 59 + this.ExportControlClassNumber.GetHashCode();
                if (this.HTSUSCode != null)
                    hashCode = hashCode * 59 + this.HTSUSCode.GetHashCode();
                if (this.TariffDescription != null)
                    hashCode = hashCode * 59 + this.TariffDescription.GetHashCode();
                if (this.MoistureSensitivityLevel != null)
                    hashCode = hashCode * 59 + this.MoistureSensitivityLevel.GetHashCode();
                if (this.Family != null)
                    hashCode = hashCode * 59 + this.Family.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.ManufacturerPartNumber != null)
                    hashCode = hashCode * 59 + this.ManufacturerPartNumber.GetHashCode();
                if (this.MinimumOrderQuantity != null)
                    hashCode = hashCode * 59 + this.MinimumOrderQuantity.GetHashCode();
                if (this.NonStock != null)
                    hashCode = hashCode * 59 + this.NonStock.GetHashCode();
                if (this.Packaging != null)
                    hashCode = hashCode * 59 + this.Packaging.GetHashCode();
                if (this.QuantityAvailable != null)
                    hashCode = hashCode * 59 + this.QuantityAvailable.GetHashCode();
                if (this.DigiKeyPartNumber != null)
                    hashCode = hashCode * 59 + this.DigiKeyPartNumber.GetHashCode();
                if (this.ProductDescription != null)
                    hashCode = hashCode * 59 + this.ProductDescription.GetHashCode();
                if (this.UnitPrice != null)
                    hashCode = hashCode * 59 + this.UnitPrice.GetHashCode();
                if (this.Manufacturer != null)
                    hashCode = hashCode * 59 + this.Manufacturer.GetHashCode();
                if (this.ManufacturerPublicQuantity != null)
                    hashCode = hashCode * 59 + this.ManufacturerPublicQuantity.GetHashCode();
                if (this.QuantityOnOrder != null)
                    hashCode = hashCode * 59 + this.QuantityOnOrder.GetHashCode();
                if (this.DKPlusRestriction != null)
                    hashCode = hashCode * 59 + this.DKPlusRestriction.GetHashCode();
                if (this.Marketplace != null)
                    hashCode = hashCode * 59 + this.Marketplace.GetHashCode();
                if (this.SupplierDirectShip != null)
                    hashCode = hashCode * 59 + this.SupplierDirectShip.GetHashCode();
                if (this.PimProductName != null)
                    hashCode = hashCode * 59 + this.PimProductName.GetHashCode();
                if (this.Supplier != null)
                    hashCode = hashCode * 59 + this.Supplier.GetHashCode();
                if (this.SupplierId != null)
                    hashCode = hashCode * 59 + this.SupplierId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
