/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


namespace DigiKey.Api.Model
{
    /// <summary>
    /// Response for list Manufacturer Product Details
    /// </summary>
    [DataContract]
    public partial class ProductDetailsResponse : IEquatable<ProductDetailsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDetailsResponse" /> class.
        /// </summary>
        /// <param name="productDetails">List of ProductDetails.</param>
        public ProductDetailsResponse(List<ProductDetails> productDetails = default(List<ProductDetails>))
        {
            this.ProductDetails = productDetails;
        }

        /// <summary>
        /// List of ProductDetails
        /// </summary>
        /// <value>List of ProductDetails</value>
        [DataMember(Name = "ProductDetails", EmitDefaultValue = false)]
        public List<ProductDetails> ProductDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductDetailsResponse {\n");
            sb.Append("  ProductDetails: ").Append(ProductDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductDetailsResponse);
        }

        /// <summary>
        /// Returns true if ProductDetailsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductDetailsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductDetailsResponse input)
        {
            if (input == null)
                return false;

            return
               (
                    this.ProductDetails == input.ProductDetails ||
                    this.ProductDetails != null &&
                    this.ProductDetails.SequenceEqual(input.ProductDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductDetails != null)
                    hashCode = hashCode * 59 + this.ProductDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
