/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;


namespace OriginalCircuit.DigiKey.Api.Model
{
    /// <summary>
    /// SearchOption - Options to search by.
    /// </summary>
    /// <value>SearchOption - Options to search by.</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum SearchOption
    {

        /// <summary>
        /// Enum ManufacturerPartSearch for value: ManufacturerPartSearch
        /// </summary>
        [EnumMember(Value = "ManufacturerPartSearch")]
        ManufacturerPartSearch = 1,

        /// <summary>
        /// Enum InStock for value: InStock
        /// </summary>
        [EnumMember(Value = "InStock")]
        InStock = 2,

        /// <summary>
        /// Enum NewProductsOnly for value: NewProductsOnly
        /// </summary>
        [EnumMember(Value = "NewProductsOnly")]
        NewProductsOnly = 3,

        /// <summary>
        /// Enum RoHSCompliant for value: RoHSCompliant
        /// </summary>
        [EnumMember(Value = "RoHSCompliant")]
        RoHSCompliant = 4,

        /// <summary>
        /// Enum LeadFree for value: LeadFree
        /// </summary>
        [EnumMember(Value = "LeadFree")]
        LeadFree = 5,

        /// <summary>
        /// Enum CollapsePackagingTypes for value: CollapsePackagingTypes
        /// </summary>
        [EnumMember(Value = "CollapsePackagingTypes")]
        CollapsePackagingTypes = 6,

        /// <summary>
        /// Enum ExcludeNonStock for value: ExcludeNonStock
        /// </summary>
        [EnumMember(Value = "ExcludeNonStock")]
        ExcludeNonStock = 7,

        /// <summary>
        /// Enum Has3DModel for value: Has3DModel
        /// </summary>
        [EnumMember(Value = "Has3DModel")]
        Has3DModel = 8,

        /// <summary>
        /// Enum HasMentorFootprint for value: HasMentorFootprint
        /// </summary>
        [EnumMember(Value = "HasMentorFootprint")]
        HasMentorFootprint = 9
    }

}
