/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;


namespace OriginalCircuit.DigiKey.Api.Model
{
    /// <summary>
    /// SortOption enum
    /// </summary>
    /// <value>SortOption enum</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum SortOption
    {

        /// <summary>
        /// Enum SortByDigiKeyPartNumber for value: SortByDigiKeyPartNumber
        /// </summary>
        [EnumMember(Value = "SortByDigiKeyPartNumber")]
        SortByDigiKeyPartNumber = 1,

        /// <summary>
        /// Enum SortByManufacturerPartNumber for value: SortByManufacturerPartNumber
        /// </summary>
        [EnumMember(Value = "SortByManufacturerPartNumber")]
        SortByManufacturerPartNumber = 2,

        /// <summary>
        /// Enum SortByDescription for value: SortByDescription
        /// </summary>
        [EnumMember(Value = "SortByDescription")]
        SortByDescription = 3,

        /// <summary>
        /// Enum SortByManufacturer for value: SortByManufacturer
        /// </summary>
        [EnumMember(Value = "SortByManufacturer")]
        SortByManufacturer = 4,

        /// <summary>
        /// Enum SortByMinimumOrderQuantity for value: SortByMinimumOrderQuantity
        /// </summary>
        [EnumMember(Value = "SortByMinimumOrderQuantity")]
        SortByMinimumOrderQuantity = 5,

        /// <summary>
        /// Enum SortByQuantityAvailable for value: SortByQuantityAvailable
        /// </summary>
        [EnumMember(Value = "SortByQuantityAvailable")]
        SortByQuantityAvailable = 6,

        /// <summary>
        /// Enum SortByUnitPrice for value: SortByUnitPrice
        /// </summary>
        [EnumMember(Value = "SortByUnitPrice")]
        SortByUnitPrice = 7,

        /// <summary>
        /// Enum SortByParameter for value: SortByParameter
        /// </summary>
        [EnumMember(Value = "SortByParameter")]
        SortByParameter = 8
    }

}
