/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;


namespace DigiKey.Api.Model
{
    /// <summary>
    /// SortOption enum
    /// </summary>
    /// <value>SortOption enum</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum SortOption
    {

        /// <summary>
        /// Enum NUMBER_SortByDigiKeyPartNumber for value: SortByDigiKeyPartNumber
        /// </summary>
        [EnumMember(Value = "SortByDigiKeyPartNumber")]
        NUMBER_SortByDigiKeyPartNumber = 1,

        /// <summary>
        /// Enum NUMBER_SortByManufacturerPartNumber for value: SortByManufacturerPartNumber
        /// </summary>
        [EnumMember(Value = "SortByManufacturerPartNumber")]
        NUMBER_SortByManufacturerPartNumber = 2,

        /// <summary>
        /// Enum NUMBER_SortByDescription for value: SortByDescription
        /// </summary>
        [EnumMember(Value = "SortByDescription")]
        NUMBER_SortByDescription = 3,

        /// <summary>
        /// Enum NUMBER_SortByManufacturer for value: SortByManufacturer
        /// </summary>
        [EnumMember(Value = "SortByManufacturer")]
        NUMBER_SortByManufacturer = 4,

        /// <summary>
        /// Enum NUMBER_SortByMinimumOrderQuantity for value: SortByMinimumOrderQuantity
        /// </summary>
        [EnumMember(Value = "SortByMinimumOrderQuantity")]
        NUMBER_SortByMinimumOrderQuantity = 5,

        /// <summary>
        /// Enum NUMBER_SortByQuantityAvailable for value: SortByQuantityAvailable
        /// </summary>
        [EnumMember(Value = "SortByQuantityAvailable")]
        NUMBER_SortByQuantityAvailable = 6,

        /// <summary>
        /// Enum NUMBER_SortByUnitPrice for value: SortByUnitPrice
        /// </summary>
        [EnumMember(Value = "SortByUnitPrice")]
        NUMBER_SortByUnitPrice = 7,

        /// <summary>
        /// Enum NUMBER_SortByParameter for value: SortByParameter
        /// </summary>
        [EnumMember(Value = "SortByParameter")]
        NUMBER_SortByParameter = 8
    }

}
