/* 
 * PartSearch Api
 *
 * Search for products and retrieve details and pricing.
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;


namespace DigiKey.Api.Model
{
    /// <summary>
    /// A value belonging to a parameter.
    /// </summary>
    [DataContract]
    public partial class ValuePair : IEquatable<ValuePair>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValuePair" /> class.
        /// </summary>
        /// <param name="valueId">The Id of the value..</param>
        /// <param name="value">The name of the value..</param>
        public ValuePair(string valueId = default(string), string value = default(string))
        {
            this.ValueId = valueId;
            this.Value = value;
        }

        /// <summary>
        /// The Id of the value.
        /// </summary>
        /// <value>The Id of the value.</value>
        [DataMember(Name = "ValueId", EmitDefaultValue = false)]
        public string ValueId { get; set; }

        /// <summary>
        /// The name of the value.
        /// </summary>
        /// <value>The name of the value.</value>
        [DataMember(Name = "Value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValuePair {\n");
            sb.Append("  ValueId: ").Append(ValueId).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValuePair);
        }

        /// <summary>
        /// Returns true if ValuePair instances are equal
        /// </summary>
        /// <param name="input">Instance of ValuePair to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValuePair input)
        {
            if (input == null)
                return false;

            return
               (
                    this.ValueId == input.ValueId ||
                   (this.ValueId != null &&
                    this.ValueId.Equals(input.ValueId))
                ) &&
               (
                    this.Value == input.Value ||
                   (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ValueId != null)
                    hashCode = hashCode * 59 + this.ValueId.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
